### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [jeppevammenkristensen/cake-ftpfolderupload#1]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by jeppevammenkristensen** [comment]
I've added the cake-contrib user in nuget. It's currently pending approval

**Comment by gep13** [comment]
@jeppevammenkristensen thank you for taking the time to do that! I have accepted the request.

Would you also be interested in moving this repository into the Cake-Contrib Organisation on GitHub? You would still have full access rights to the repository in the same way as you do now, it’s just that the repository would live under an organisation. This is part of our, the Cake Teams, attempt to consolidate development effort into one place, to ensure the longevity of the addins that are created for Cake.

Please let me know if you have any questions.

Thanks

**Comment by jeppevammenkristensen** [comment]
Hi @gep13 Better late than never. Sorry it's taken so long. How do I go about transferring it to Cake-Contrib?

**Comment by gep13** [comment]
@jeppevammenkristensen the process for moving an addin into the Organisation is documented here:

https://github.com/cake-contrib/home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

The only part that is required to be completed by yourself would be the first one.  From there, someone in the team can handle the rest, and get you set up with access to the repository/CI once everything is transferred, to allow you to continue working on the addin.

**Comment by jeppevammenkristensen** [comment]
@gep13 Yesterday I tried to transfer it directly to the Cake-Contrib organisation. I couldn't do that, so I've initiated a transfer to your account

**Comment by gep13** [comment]
@jeppevammenkristensen that is correct.  Unless you are an owner of the Organisation, you can't transfer a repository directly into the organisation, which is a little bit of a pain 😿 

I got the request to transfer to me, and as you will hopefully see, the repository has now been transferred into the Cake Contrib Organisation.  I have also sent you a request to join the Organisation, and once you do, you should have full admin rights to the repository in the same way as you did before.

There is still a little bit of work to do to setup other permissions, but I will take care of this when I can.

Please let me know if you have any questions.

**Comment by gep13** [comment]
I think we got this taken care of, so I am going to close out this issue.
